# Site setings
name: 'Obscure Dinosaur Facts'
description: 'A blog by paleoartist Clara Takahashi'
title_image: 'author.png'
meta_description: ''
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'author.png'
  greetings: "Here you will find facts about obscure dinosaurs, obscure facts about well-known dinosaurs, and other material covering such topics as evolution, taxonomy, geology, and pop culture!"
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://obscuredinosaurfacts.com/
# disqus: ''
# mailchimp_url: ''
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: obscure.dinosaur.facts@gmail.com
contact_page_description: ""
thankyou_page_description: "Your message has been successfully sent. We will contact you soon!"

# Social links
twitter: 'clynnetakahashi'
# facebook: 'username'
github: 'roscoestar'
# codepen: 'username'
# dribbble: 'username'
# medium: '@username'
instagram: 'claratakahashi'
# pinterest: 'username'
linkedin: 'clara-takahashi'
# producthunt: '@username'
# quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Art
    url: /art
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:categories/:year/:month/:day/:title:output_ext

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
